CC     = gcc
CFLAGS = -std=c11 -fopenmp -Wall -Wextra -Wpedantic -O2 -g
LDLIBS = -lm

checkpoint: checkpoint.c

checkpoint_fsync: checkpoint_fsync.c

checkpoint_optimized: checkpoint_optimized.c

clean:
	$(RM) checkpoint
